openapi: 3.0.2

info:
  title: Orm Comparison API
  description: Test project for ORM mechanics comparison purpose
  contact:
    name: Andrew Belunov
    email: cyberpunk.perosn@gmail.com
  version: 1.0.0

tags:
  - name: items
    description: Items in the store
  - name: orders
    description: Orders form with items by users
  - name: users
    description: Users of the store

paths:

  /items:

    get:
      tags:
        - items
      summary: getItems
      description: Get all existing items
      operationId: getItems
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetItemsResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

    put:
      tags:
        - items
      summary: putItem
      description: Save or update existing item
      operationId: putItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutItemRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutItemResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /items/{itemId}:

    parameters:
      - $ref: '#/components/parameters/ItemId'

    get:
      tags:
        - items
      summary: getItemById
      description: Get item by id
      operationId: getItemById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetItemResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /orders:

    put:
      tags:
        - orders
      summary: putOrder
      description: Save or update existing order
      operationId: putOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutOrderRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutOrderResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'


    get:
      tags:
        - orders
      summary: getOrders
      description: Get all existing orders
      operationId: getOrders
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrdersResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /orders/{orderId}:

    parameters:
      - $ref: '#/components/parameters/OrderId'

    get:
      tags:
        - orders
      summary: getOrderById
      description: Get order by id
      operationId: getOrderById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /orders/address/{addressId}:

    parameters:
      - $ref: '#/components/parameters/AddressId'

    get:
      tags:
        - orders
      summary: getOrdersByAddressId
      description: Get orders by addressId
      operationId: getOrdersByAddressId
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrdersResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /orders/contain-items:

    post:
      tags:
        - orders
      summary: getOrdersByItemsId
      description: Get orders by items id
      operationId: getOrdersByItemsId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetOrderByItemsIdRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrdersResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /users:

    put:
      tags:
        - users
      summary: putUser
      description: Save or update existing user
      operationId: putUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutUserRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutUserResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

    get:
      tags:
        - users
      summary: getUsers
      description: Get all existing users
      operationId: getUsers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /users/{userId}:

    parameters:
      - $ref: '#/components/parameters/UserId'

    get:
      tags:
        - users
      summary: getUserById
      description: Get user by id
      operationId: getUserById
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

components:

  parameters:
    ItemId:
      description: Item id (generates by frontend to avoid dublications)
      name: itemId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 127aee00-fa63-4eff-a7a6-a4bc21118776

    OrderId:
      description: Order id (generates by frontend to avoid dublications)
      name: orderId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 127aee00-fa63-4eff-a7a6-a4bc21118776

    UserId:
      description: User id (generates by frontend to avoid dublications)
      name: userId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 127aee00-fa63-4eff-a7a6-a4bc21118776

    AddressId:
      description: Address id (generates by frontend to avoid dublications)
      name: addressId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 127aee00-fa63-4eff-a7a6-a4bc21118776

  responses:

    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:

    GetItemsResponse:
      type: object
      required:
        - items
      properties:
        items:
          description: List of existing items
          type: array
          items:
            $ref: '#/components/schemas/Item'

    GetItemResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/Item'

    PutItemRequest:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/Item'

    PutItemResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/Item'

    GetOrdersResponse:
      type: object
      required:
        - items
      properties:
        items:
          description: List of existing orders
          type: array
          items:
            $ref: '#/components/schemas/Order'

    GetOrderResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/Order'

    GetOrderByItemsIdRequest:
      type: object
      required:
        - payload
      properties:
        payload:
          type: array
          minLength: 1
          items:
              type: string
              format: uuid

    PutOrderRequest:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/Order'

    PutOrderResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/Order'

    GetUsersResponse:
      type: object
      required:
        - items
      properties:
        items:
          description: List of existing users
          type: array
          items:
            $ref: '#/components/schemas/User'

    GetUserResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/User'

    PutUserRequest:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/User'

    PutUserResponse:
      type: object
      required:
        - payload
      properties:
        payload:
          $ref: '#/components/schemas/User'


    Item:
      description: Item in the store
      type: object
      required:
        - id
        - title
        - description
        - price
      properties:
        id:
          description: Item identificator
          type: string
          format: uuid
          example: 397aee00-f163-4eff-a7a6-a4bc11118776
        title:
          description: Item's title
          type: string
          minLength: 1
          example: Example Title
        description:
          description: Item's description
          type: string
          minLength: 1
          example: Example desecription
        price:
          description: Item's price
          type: big-decimal

    Order:
      description: Order in the store
      type: object
      required:
        - id
        - userId
        - address
        - items
      properties:
        id:
          description: order identificator
          type: string
          format: uuid
          example: 397aee00-f163-4eff-a7a6-a4bc11118776
        userId:
          description: userId who formed order
          type: string
          format: uuid
          example: 397aee00-f163-4eff-a7a6-a4bc11118776
        address:
          $ref: '#/components/schemas/Address'
        items:
          description: Items in the order
          type: array
          items:
            $ref: '#/components/schemas/Item'

    User:
      description: User in the store
      type: object
      required:
        - id
        - name
        - address
      properties:
        id:
          description: User identificator
          type: string
          format: uuid
          example: 397aee00-f163-4eff-a7a6-a4bc11118776
        name:
          description: User name
          type: string
          example: Ivan
        address:
          description: User's address
          $ref: '#/components/schemas/Address'

    Address:
      description: User's address
      type: object
      required:
        - id
        - country
        - city
        - street
        - zip
      properties:
        id:
          description: Address identificator
          type: string
          format: uuid
          example: 397aee00-f163-4eff-a7a6-a4bc11118776
        country:
          type: string
          example: Russia
        city:
          type: string
          example: Krasnoyarsk
        street:
          type: string
          example: Mira
        zip:
          type: integer
          example: 640441

    ErrorResponse:
      description: Error response
      type: object
      required:
        - errorId
        - errorCode
        - errorMessage
      properties:
        errorId:
          description: Error identificator
          type: string
          minLength: 16
          maxLength: 16
          example: 02d55cabb05b44f0
        errorCode:
          description: Service error code
          type: string
          minLength: 1
          example: InternalServerError
        errorMessage:
          description: service error message
          type: string
          minLength: 1
          example: Internal server error
        errorDetails:
          description: Error details
          type: object